# -*- coding: utf-8 -*-
"""EcommercePurchasesExercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MC0PnxKSD8m0qifMQRJxvVIYxn0u3UQc
"""

import pandas as pd
ecom = pd.read_csv('Ecommerce Purchases')
# Check the head of the DataFrame
ecom.head()

# How many rows and columns are there?
ecom.shape

# What is the average Purchase Price?
ecom['Purchase Price'].mean()

# What were the highest and lowest purchase prices?
print(ecom['Purchase Price'].max())
print(ecom['Purchase Price'].min())

# How many people have English 'en' as their Language of choice on the website?
def string_correction(title):
  if 'en' in title.lower().split():
    return True
  else:
    return False
sum(ecom['Language'].apply(lambda x: string_correction(x)))

# How many people have the job title of "Lawyer" ? 
ecom[ecom['Job'] == 'Lawyer'].count()

# How many people made the purchase during the AM and how many people made the purchase during PM ?
ecom.groupby('AM or PM').count()
# AM: 4932 - PM: 5068

# What are the 5 most common Job Titles?
ecom['Job'].value_counts().head(5)

# Someone made a purchase that came from Lot: "90 WT" , what was the Purchase Price for this transaction?
ecom[ecom['Lot'] == '90 WT']['Purchase Price']

# What is the email of the person with the following Credit Card Number: 4926535242672853
ecom[ecom['Credit Card'] == 4926535242672853]['Email']

# How many people have American Express as their Credit Card Provider "and" made a purchase above $95 ?
ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95)].count()

# How many people have a credit card that expires in 2025?
ecom[['Month', 'Year']] = ecom['CC Exp Date'].str.split('/', expand=True)
ecom[ecom['Year'].astype(int) == 25].count()

# What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc...)
ecom[['Nick', 'Email Provider']] = ecom['Email'].str.split('@', expand=True)
ecom['Email Provider'].value_counts().head(5)